### ISSUE TITLE
[Feature]: enable pwa

### ISSUE THREAD

**Issue by ashishkpaul** [vuestorefront-community/prestashop#31]
### How the project can be improved?

Good to have web and mobile apps

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
Hello,
would you please explain more? thanks

**Comment by ashishkpaul** [comment]
hello sir, I mean to say, vuestorefront has a feature of pwa to take the advantage of service worker caching, push notifications, responsive design etc.

Please add these feacutres too in a vue-prestashop frontend

![PWA-Native-app-functionalities](https://user-images.githubusercontent.com/16308863/170808662-148daa43-1b7a-479b-b54f-7989bff693f2.jpg)

**Comment by samberrry** [comment]
of course it supports.

Vue Storefront uses `@nuxtjs/pwa` module which adds support for PWA functionalities: 
https://docs.vuestorefront.io/v2/getting-started/theme.html

Vue Storefront is mainly a NuxtJs application, that we can benefit from all Nuxtjs features. 
You can also read more about the PWA:
https://pwa.nuxtjs.org/

**Comment by ashishkpaul** [comment]
Thanks sir,

**Comment by samberrry** [comment]
@ashishkpaul welcome.
