### ISSUE TITLE
[Bug]: Menus are not working  on mobile 

### ISSUE THREAD

**Issue by ashishkpaul** [vuestorefront-community/prestashop#32]
### Expected Behavior

Menus are not navigating w.r.t products on a mobile 

### Actual Behavior

Category Menus are not working or navigate 

### Steps to reproduce

On a mobile browser click on menu then try to navigate categories menus 
![Screenshot_20220527-211037_Chrome](https://user-images.githubusercontent.com/16308863/170734028-d809d713-543a-40f7-8c94-15d0146cd68c.jpg)

### What version of PrestaShop integration are you using?

1.7.x

### What version of Node.js are you using?

v14.19.2

### What browser (and version) are you using?

Mobile Google Chrome 

### What operating system (and version) are you using?

Ubuntu 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
fixed https://github.com/vuestorefront-community/prestashop/pull/55

**Comment by ashishkpaul** [comment]
Thanks sir
