### ISSUE TITLE
Unable to change theme colors ,tried every but it didn't worked

### ISSUE THREAD

**Issue by derarsat** [vuestorefront-community/prestashop#41]
### Provide a description of requested docs changes

Please describe how the theme colors and fonts can be changed

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
> ### Provide a description of requested docs changes
> 
> Please describe how the theme colors and fonts can be changed
> ### Able to fix / change the documentation?
> 
>     * [ ]  Yes
> 
>     * [x]  No
> 
> 
> ### Code of Conduct
> 
>     * [x]  I agree to follow this project's Code of Conduct

You can check these tutorials for find out:
https://www.youtube.com/watch?v=dwj2snJegYU
https://www.youtube.com/watch?v=wwmzrgrXdyo
https://www.youtube.com/watch?v=uCxPb_39TNg

**Comment by derarsat** [comment]
@samberrry i watched this tutorials, but i can't find index.vue file to modify
