### ISSUE TITLE
[Bug]: Not redirecting to checkout page

### ISSUE THREAD

**Issue by ashishkpaul** [vuestorefront-community/prestashop#59]
### Expected Behavior

cart should move to checkout page

### Actual Behavior

Same as title

![Screenshot_2022-11-04_10-14-29](https://user-images.githubusercontent.com/16308863/199889995-eeb039ca-31b4-429e-8e87-808d39ac5626.png)

### What version of PrestaShop integration are you using?

v1.1.0

### What version of Node.js are you using?

v14.19.3

### What browser (and version) are you using?

Chrome, Firefox

### What operating system (and version) are you using?

Linux ( Debian )

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashishkpaul** [comment]
Sorry sir, my Nginx config was wrong

**Comment by samberrry** [comment]
thanks for reporting. 
I re-open this issue, because I faced the same issue on v1.10.

**Comment by samberrry** [comment]
fixed in v1.1.1

**Comment by ashishkpaul** [comment]
Hello sir, I just checked that now its navigating to checkout page but **checkout button is deactivate** when we reached on shipping method.
![Screenshot_20221114-174401_Chrome](https://user-images.githubusercontent.com/16308863/201658625-9aaedf92-4ffa-42bb-941c-99810476e0f4.jpg)

**Comment by ashishkpaul** [comment]
I will try again sir, thanks
