### ISSUE TITLE
[Bug]:  The total and subtotal prices in the checkout steps are incorrect 

### ISSUE THREAD

**Issue by noori1995** [vuestorefront-community/prestashop#67]
### Expected Behavior

The total and subtotal prices in the checkout steps are correct 

### Actual Behavior

The total and subtotal prices in the checkout steps are incorrect 

### What version of PrestaShop integration are you using?

any

### What version of Node.js are you using?

16.18.1

### What browser (and version) are you using?

chrome

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samberrry** [comment]
Shipping price must be added too.
