### ISSUE TITLE
[Bug]: Allows adding unlimited number of products - stop customer proceeding with checkout when there is an out-of-stock product in cart

### ISSUE THREAD

**Issue by GuillaumeDgr** [vuestorefront-community/prestashop#74]
### Actual Behavior

VSF quantities are not linked with prestashop back-office, I can add unlimited quantity for one product even if there is only one unit of this product left on the back office.

### What version of PrestaShop integration are you using?

1.7.8.3

### What version of Node.js are you using?

16.14.2

### What browser (and version) are you using?

Mozilla Firefox Developers

### What operating system (and version) are you using?

macOS

**Comment by samberrry** [comment]
I checked the issue on the PrestaShop default theme, please take a look at the PrestaShop default behavior:

![Screen Shot 2022-12-02 at 8 01 25 PM](https://user-images.githubusercontent.com/20775532/205414865-d213da78-7026-4391-a616-5fd240785b5e.png)

You see that we can add unlimited number of products even more than the in-stock quantity, but we can not proceed with the checkout, so we can not limit add to cart however we can stop customer to go further. 

I will change the issue to "Stop customer proceeding with checkout when there is a out-of-stock/quantity product in cart".

**Comment by samberrry** [comment]
JFYI, if you are using virtual products, there is also an issue for virtual products in default Ps, it allows adding unlimited products, also it does not stop customer from proceeding to checkout: https://github.com/PrestaShop/PrestaShop/issues/28958

**Comment by samberrry** [comment]
Cart error handling feature: 
https://github.com/vuestorefront-community/prestashop/pull/85

Will be added in v1.2.0
